<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\eAgendaWeb\eAgendaWeb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\eAgendaWeb.DataBase\dbo\Tables\TBCategoria.sql"
          Link="Scripts\TBCategoria.sql"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\eAgendaWeb.DataBase\dbo\Tables\TBDespesa.sql"
          Link="Scripts\TBDespesa.sql"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\eAgendaWeb.DataBase\dbo\Tables\TBDespesaCategoria.sql"
          Link="Scripts\TBDespesaCategoria.sql"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\eAgendaWeb.DataBase\dbo\Tables\TBContato.sql"
          Link="Scripts\TBContato.sql"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\eAgendaWeb.DataBase\dbo\Tables\TBCompromisso.sql"
          Link="Scripts\TBCompromisso.sql"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\eAgendaWeb.DataBase\dbo\Tables\TBTarefa.sql"
          Link="Scripts\TBTarefa.sql"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\eAgendaWeb.DataBase\dbo\Tables\TBItemTarefa.sql"
          Link="Scripts\TBItemTarefa.sql"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
